# Docker contianer used to seed MongoDB with data

# Extends MongoDB
# Note - the Mongo database in this container isn't used actually used at all.
# We use the `mongoimport` command line utility on this container to populate the other Mongo container with data.
FROM mongo

# Copies seed/*.json
# QUESTON - can copy directory?
COPY seed/achievements.json /achievements.json
COPY seed/attendances.json /attendances.json
COPY seed/classyears.json /classyears.json
COPY seed/posts.json /posts.json
COPY seed/projects.json /projects.json
COPY seed/smallgroups.json /smallgroups.json
COPY seed/users.json /users.json

# Imports each collection into MongoDB
CMD echo "Seeding MongoDB" && \
mongoimport --host mongodb --db observatory-dev --collection achievements --type json --file ./achievements.json --jsonArray && \
mongoimport --host mongodb --db observatory-dev --collection attendances --type json --file ./attendances.json --jsonArray && \
mongoimport --host mongodb --db observatory-dev --collection classyears --type json --file ./classyears.json --jsonArray && \
mongoimport --host mongodb --db observatory-dev --collection posts --type json --file ./posts.json --jsonArray && \
mongoimport --host mongodb --db observatory-dev --collection projects --type json --file ./projects.json --jsonArray && \
mongoimport --host mongodb --db observatory-dev --collection smallgroups --type json --file ./smallgroups.json --jsonArray && \
mongoimport --host mongodb --db observatory-dev --collection users --type json --file ./users.json --jsonArray
